# Generated by Django 2.1.1 on 2018-09-30 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('AR', 'aerobic'), ('ST', 'Strength'), ('BA', 'Balance'), ('FL', 'Flexibility')], max_length=20)),
                ('weight', models.FloatField()),
                ('weight_units', models.CharField(choices=[('KG', 'Kilograms'), ('LB', 'Pounds')], max_length=20)),
                ('sets', models.IntegerField()),
                ('duration', models.TimeField()),
                ('muscle_target', models.CharField(max_length=400)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workouts', models.ManyToManyField(to='tracker.Exercise')),
            ],
        ),
    ]
